<option <?php if ($klas == '01') { ?>selected <?php }; ?>value="01">HOD1a</option>
<option <?php if ($klas == '02') { ?>selected <?php }; ?>value="02">HOD1b</option>
<option <?php if ($klas == '03') { ?>selected <?php }; ?>value="03">HOD3x</option>
<option <?php if ($klas == '04') { ?>selected <?php }; ?>value="04">HVK1a</option>
<option <?php if ($klas == '05') { ?>selected <?php }; ?>value="05">HVK1b</option>
<option <?php if ($klas == '06') { ?>selected <?php }; ?>value="06">HVK1c</option>
<option <?php if ($klas == '07') { ?>selected <?php }; ?>value="07">HVK2a</option>
<option <?php if ($klas == '08') { ?>selected <?php }; ?>value="08">HVK2b</option>
<option <?php if ($klas == '09') { ?>selected <?php }; ?>value="09">HVKS2</option>
<option <?php if ($klas == '10') { ?>selected <?php }; ?>value="10">HVS2a</option>
<option <?php if ($klas == '11') { ?>selected <?php }; ?>value="11">HVS2b</option>
<option <?php if ($klas == '12') { ?>selected <?php }; ?>value="12">MHM1</option>
<option <?php if ($klas == '13') { ?>selected <?php }; ?>value="13">VKD1</option>
<option <?php if ($klas == '14') { ?>selected <?php }; ?>value="14">VKM1</option>
<option <?php if ($klas == '15') { ?>selected <?php }; ?>value="15">VKW1</option>
<option <?php if ($klas == '16') { ?>selected <?php }; ?>value="16">VSD1</option>
<option <?php if ($klas == '17') { ?>selected <?php }; ?>value="17">VSM1</option>
<option <?php if ($klas == '18') { ?>selected <?php }; ?>value="18">VSW1</option>