<option <?php if ($klas == '01') { ?>selected <?php }; ?>value="01">AD2H</option>
<option <?php if ($klas == '02') { ?>selected <?php }; ?>value="02">AD3A</option>
<option <?php if ($klas == '03') { ?>selected <?php }; ?>value="03">AD4A</option>
<option <?php if ($klas == '04') { ?>selected <?php }; ?>value="04">AM1A</option>
<option <?php if ($klas == '05') { ?>selected <?php }; ?>value="05">AM1B</option>
<option <?php if ($klas == '06') { ?>selected <?php }; ?>value="06">AM2A</option>
<option <?php if ($klas == '07') { ?>selected <?php }; ?>value="07">AM2B</option>
<option <?php if ($klas == '08') { ?>selected <?php }; ?>value="08">DS1A</option>
<option <?php if ($klas == '09') { ?>selected <?php }; ?>value="09">DS2A</option>
<option <?php if ($klas == '10') { ?>selected <?php }; ?>value="10">DS3A</option>
<option <?php if ($klas == '11') { ?>selected <?php }; ?>value="11">DS4A</option>
<option <?php if ($klas == '12') { ?>selected <?php }; ?>value="12">FB1A</option>
<option <?php if ($klas == '13') { ?>selected <?php }; ?>value="13">FB1B</option>
<option <?php if ($klas == '14') { ?>selected <?php }; ?>value="14">FB1C</option>
<option <?php if ($klas == '15') { ?>selected <?php }; ?>value="15">FM2A</option>
<option <?php if ($klas == '16') { ?>selected <?php }; ?>value="16">FM2B</option>
<option <?php if ($klas == '17') { ?>selected <?php }; ?>value="17">IB1D</option>
<option <?php if ($klas == '18') { ?>selected <?php }; ?>value="18">IB2D</option>
<option <?php if ($klas == '19') { ?>selected <?php }; ?>value="19">IO1A</option>
<option <?php if ($klas == '20') { ?>selected <?php }; ?>value="20">IO2A</option>
<option <?php if ($klas == '21') { ?>selected <?php }; ?>value="21">IO3A</option>
<option <?php if ($klas == '22') { ?>selected <?php }; ?>value="22">IT4A</option>
<option <?php if ($klas == '23') { ?>selected <?php }; ?>value="23">JD1A</option>
<option <?php if ($klas == '24') { ?>selected <?php }; ?>value="24">MB1A</option>
<option <?php if ($klas == '25') { ?>selected <?php }; ?>value="25">MB2A</option>
<option <?php if ($klas == '26') { ?>selected <?php }; ?>value="26">MC1A</option>
<option <?php if ($klas == '27') { ?>selected <?php }; ?>value="27">MC1B</option>
<option <?php if ($klas == '28') { ?>selected <?php }; ?>value="28">MC2A</option>
<option <?php if ($klas == '29') { ?>selected <?php }; ?>value="29">MC3A</option>
<option <?php if ($klas == '30') { ?>selected <?php }; ?>value="30">MT1A</option>
<option <?php if ($klas == '31') { ?>selected <?php }; ?>value="31">MT2A</option>
<option <?php if ($klas == '32') { ?>selected <?php }; ?>value="32">SE1A</option>
<option <?php if ($klas == '33') { ?>selected <?php }; ?>value="33">SE2A</option>