<?php
if ($klas == '01') { $sklas = "AD2A";}
if ($klas == '02') { $sklas = "AD3A";}
if ($klas == '03') { $sklas = "AD4A";}
if ($klas == '04') { $sklas = "AM1A";}
if ($klas == '05') { $sklas = "AM1B";}
if ($klas == '06') { $sklas = "AM2A";}
if ($klas == '07') { $sklas = "AM2B";}
if ($klas == '08') { $sklas = "DS1A";}
if ($klas == '09') { $sklas = "DS2A";}
if ($klas == '10') { $sklas = "DS3A";}
if ($klas == '11') { $sklas = "FB1A";}
if ($klas == '12') { $sklas = "FB1B";}
if ($klas == '13') { $sklas = "FB1C";}
if ($klas == '14') { $sklas = "FM2A";}
if ($klas == '15') { $sklas = "FM2B";}
if ($klas == '16') { $sklas = "IB1D";}
if ($klas == '17') { $sklas = "IB2D";}
if ($klas == '18') { $sklas = "IO1A";}
if ($klas == '19') { $sklas = "IO2A";}
if ($klas == '20') { $sklas = "IO3A";}
if ($klas == '21') { $sklas = "IT4A";}
if ($klas == '22') { $sklas = "JD1A";}
if ($klas == '23') { $sklas = "MB1A";}
if ($klas == '24') { $sklas = "MB2A";}
if ($klas == '25') { $sklas = "MC1A";}
if ($klas == '26') { $sklas = "MC1B";}
if ($klas == '27') { $sklas = "MC2A";}
if ($klas == '28') { $sklas = "MC3A";}
if ($klas == '29') { $sklas = "MT1A";}
if ($klas == '30') { $sklas = "MT2A";}
if ($klas == '31') { $sklas = "SE1A";}
if ($klas == '32') { $sklas = "SE2A";}
?>